name: kap
description: Kap mobile.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: 4.6.5
  auto_route: ^7.7.1
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  package_info_plus: ^4.0.2
  hive: ^2.2.3
  path_provider: ^2.0.15
  flutter_svg: ^2.0.7
  ui_kit:
    git:
      url: https://gitlab+deploy-token-15:VHgqxEZuBFgR7Pu7gyxf@assets.kap.com/ui_kit.git
      ref: fe54d9d01a7022b667f433c5c21344beed958844

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  auto_route_generator: ^7.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Red Hat Display
      fonts:
        - asset: assets/fonts/red_hat_display/RedHatDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/red_hat_display/RedHatDisplay-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/red_hat_display/RedHatDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/red_hat_display/RedHatDisplay-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/red_hat_display/RedHatDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/red_hat_display/RedHatDisplay-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/red_hat_display/RedHatDisplay-SemiBold.otf
          weight: 600
        - asset: assets/fonts/red_hat_display/RedHatDisplay-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/red_hat_display/RedHatDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/red_hat_display/RedHatDisplay-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/red_hat_display/RedHatDisplay-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/red_hat_display/RedHatDisplay-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/red_hat_display/RedHatDisplay-Black.otf
          weight: 900
        - asset: assets/fonts/red_hat_display/RedHatDisplay-BlackItalic.otf
          weight: 900
          style: italic

    - family: Panchang
      fonts:
        - asset: assets/fonts/panchang/Panchang-Light.otf
          weight: 300
        - asset: assets/fonts/panchang/Panchang-Regular.otf
          weight: 400
        - asset: assets/fonts/panchang/Panchang-Medium.otf
          weight: 500
        - asset: assets/fonts/panchang/Panchang-SemiBold.otf
          weight: 600
        - asset: assets/fonts/panchang/Panchang-Bold.otf
          weight: 700
        - asset: assets/fonts/panchang/Panchang-ExtraBold.otf
          weight: 800
